---
ID: "7996ba47-ca98-5826-8700-377fac7a7cc1"
Parent: "a8343061-92ff-5268-ac22-358bd8ddb458"
Template: "a8343061-92ff-5268-ac22-358bd8ddb458"
Path: "/sitecore/templates/Project/sitecore-docker-nextjs/Styleguide-ComponentParams Rendering Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210612T013429Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d6f10f83-7b26-4859-a876-7fde7c605e42"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210612T013429Z
