---
ID: "2dfe0446-7082-55fd-9fbf-e7cfbb2b16f3"
Parent: "1cee75a6-4c3b-5864-a019-0de92864e5ca"
Template: "1cee75a6-4c3b-5864-a019-0de92864e5ca"
Path: "/sitecore/templates/Project/sitecore-docker-nextjs/Styleguide-FieldUsage-Number/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210612T013426Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "84dce45e-6f79-4afb-879f-964c3fd34946"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210612T013426Z
