---
ID: "17f18cc4-620e-5aeb-b4be-9fa29ccb0e96"
Parent: "9a859d2d-99f4-5ef3-8be0-8bcc9ecd4a29"
Template: "9a859d2d-99f4-5ef3-8be0-8bcc9ecd4a29"
Path: "/sitecore/templates/Project/sitecore-docker-nextjs/Styleguide-FieldUsage-Image/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210612T013425Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "391524f9-61c5-4c0a-a139-e9f4fbe6127f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210612T013425Z
